//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.04 at 10:29:03 PM BRST 
//


package br.com.ntk.transacao;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cartao complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cartao">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numCartao" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="validade">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="mes" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="ano" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="via" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="tipo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cartao", propOrder = {
    "numCartao",
    "validade",
    "via",
    "tipo"
})
public class Cartao {

    @XmlElement(required = true)
    protected String numCartao;
    @XmlElement(required = true)
    protected Cartao.Validade validade;
    protected int via;
    protected int tipo;

    /**
     * Gets the value of the numCartao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumCartao() {
        return numCartao;
    }

    /**
     * Sets the value of the numCartao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumCartao(String value) {
        this.numCartao = value;
    }

    /**
     * Gets the value of the validade property.
     * 
     * @return
     *     possible object is
     *     {@link Cartao.Validade }
     *     
     */
    public Cartao.Validade getValidade() {
        return validade;
    }

    /**
     * Sets the value of the validade property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cartao.Validade }
     *     
     */
    public void setValidade(Cartao.Validade value) {
        this.validade = value;
    }

    /**
     * Gets the value of the via property.
     * 
     */
    public int getVia() {
        return via;
    }

    /**
     * Sets the value of the via property.
     * 
     */
    public void setVia(int value) {
        this.via = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     */
    public int getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     */
    public void setTipo(int value) {
        this.tipo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="mes" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="ano" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Validade {

        @XmlAttribute(name = "mes", required = true)
        protected int mes;
        @XmlAttribute(name = "ano", required = true)
        protected int ano;

        /**
         * Gets the value of the mes property.
         * 
         */
        public int getMes() {
            return mes;
        }

        /**
         * Sets the value of the mes property.
         * 
         */
        public void setMes(int value) {
            this.mes = value;
        }

        /**
         * Gets the value of the ano property.
         * 
         */
        public int getAno() {
            return ano;
        }

        /**
         * Sets the value of the ano property.
         * 
         */
        public void setAno(int value) {
            this.ano = value;
        }

    }

}
