//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.04 at 10:29:03 PM BRST 
//


package br.com.ntk.transacao;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.ntk.transacao package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Transacao_QNAME = new QName("http://www.ntk.com.br/transacao", "transacao");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.ntk.transacao
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cartao }
     * 
     */
    public Cartao createCartao() {
        return new Cartao();
    }

    /**
     * Create an instance of {@link Transacao }
     * 
     */
    public Transacao createTransacao() {
        return new Transacao();
    }

    /**
     * Create an instance of {@link Cartao.Validade }
     * 
     */
    public Cartao.Validade createCartaoValidade() {
        return new Cartao.Validade();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Transacao }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ntk.com.br/transacao", name = "transacao")
    public JAXBElement<Transacao> createTransacao(Transacao value) {
        return new JAXBElement<Transacao>(_Transacao_QNAME, Transacao.class, null, value);
    }

}
