//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.04 at 10:29:03 PM BRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ntk.com.br/transacao", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.ntk.transacao;
